version: 0.1

environment_variables:
  plaintext:
            
phases:
  install:
    commands:
  pre_build:
    commands:
      - "dotnet restore"
  build:
    commands:
      - "dotnet build"
  post_build:
    commands:
      - "dotnet publish -o target/oidc"
      - "cd target && zip -r oidc.zip oidc"
artifacts:
  files:
    - "oidc.zip"
  discard-paths: "yes"
  base-directory: "target"